version: "3.7"

services:

  nginx:
    user: root
    build:
      context: _docker/nginx
      dockerfile: nginx.dockerfile
    volumes:
      - ./:/var/www
    depends_on:
      - php-fpm
      - php-cli
    ports:
      - 80:80
      - 443:443

  php-fpm:
    user: root
    build:
      context: _docker/php
      dockerfile: php-fpm.dockerfile
    volumes:
      - ./:/var/www
    depends_on:
      - postgres
    env_file:
      - .env
      - _docker/environment.env

  php-cli:
    user: root
    build:
      context: _docker/php
      dockerfile: php-cli.dockerfile
    volumes:
      - ./:/var/www
    depends_on:
      - postgres
    env_file:
      - .env
      - _docker/environment.env
    tty: true

  postgres:
    user: root
    image: postgres:12-alpine
    volumes:
      - ./storage/docker/postgres:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432
    env_file:
      - .env
      - _docker/environment.env
    restart: unless-stopped