GET http://localhost/api/balance/241
Content-Type: application/json

###
PUT http://localhost/api/balance/241
Content-Type: application/json

{
  "value":  "100",
  "transaction_type": "debit",
  "currency":  "RUB",
  "change_reason": "stock"
}

###
PUT http://localhost/api/balance/241
Content-Type: application/json

{
  "value":  "100",
  "transaction_type": "credit",
  "currency":  "RUB",
  "change_reason": "stock"
}

###
PUT http://localhost/api/balance/241
Content-Type: application/json

{
  "value":  "100",
  "transaction_type": "debit",
  "currency":  "USD",
  "change_reason": "stock"
}

###
PUT http://localhost/api/balance/241
Content-Type: application/json

{
  "value":  "100",
  "transaction_type": "credit",
  "currency":  "USD",
  "change_reason": "stock"
}
